#### Analysis of the Cancer Prevalence in United States of America

##### Importing relevant libraries

In [84]:
# Importing Pandas as Numpy 

import pandas as pd
import numpy as np

#### Importing the dataset

##### We shall be using the America Cancer Centre website dataset https://cancerstatisticscenter.cancer.org/#!/?module=BmVYeqHT

##### Importing the Incident rate dataset

In [85]:
incident_rate_df = pd.read_excel("IncRate.xlsx", sheet_name =1,header = 6,index_col = 'State')
incident_rate_df.drop(incident_rate_df.index[:5],inplace=True)

# Displaying the first five records

incident_rate_df.head(5)

                     All cancer types combined / Both sexes combined  ... Uterine corpus / Male
State                                                                 ...
California                                                     402.4  ...                   NaN
Colorado                                                       396.7  ...                   NaN
Connecticut                                                    465.1  ...                   NaN
Delaware                                                       488.2  ...                   NaN
District of Columbia                                             426  ...                   NaN

[5 rows x 78 columns]

In [3]:
incident_rate_df.shape

(48, 78)

##### Importing the New Cases Estimates dataset

In [4]:
new_case_estimates_df = pd.read_excel("NewCaseEstimates.xlsx", sheet_name =1,header = 6,index_col = 'State')

new_case_estimates_df.drop(new_case_estimates_df.index[:5],inplace=True)
# Displaying the first five records

new_case_estimates_df.head(5)

                     All cancer types combined  ...  Vulva
State                                           ...
California                              189220  ...    NaN
Colorado                                 28480  ...    NaN
Connecticut                              22810  ...    NaN
Delaware                                  7080  ...    NaN
District of Columbia                      3440  ...    NaN

[5 rows x 57 columns]

**ALL US INC RATE DATASET**

In [73]:
all_us_df = pd.read_excel("IncRate.xlsx", sheet_name =0, header = 6)
all_us_df

                         Cancer Type  ...   Male
0          All cancer types combined  ...  487.9
1     Brain and other nervous system  ...    7.6
2                             Breast  ...    NaN
3                             Cervix  ...    NaN
4           Colon (excluding rectum)  ...   28.1
5                         Colorectum  ...   42.1
6                          Esophagus  ...    7.8
7                   Hodgkin lymphoma  ...    3.0
8            Kidney and renal pelvis  ...   23.2
9                             Larynx  ...    5.4
10                          Leukemia  ...   18.1
11  Liver and intrahepatic bile duct  ...   13.1
12                 Lung and bronchus  ...   65.8
13              Melanoma of the skin  ...   28.9
14                           Myeloma  ...    8.6
15              Non-Hodgkin lymphoma  ...   23.1
16           Oral cavity and pharynx  ...   18.1
17                             Ovary  ...    NaN
18                          Pancreas  ...   14.9
19                          Prostate  ...  106.4
20                            Rectum  ...   13.9
21                           Stomach  ...    8.7
22                            Testis  ...    5.7
23                           Thyroid  ...    7.3
24                   Urinary bladder  ...   34.0
25                    Uterine corpus  ...    NaN

[26 rows x 4 columns]

In [81]:
#all_us_df.columns=all_us_df.columns.str.strip().str.lower().str.replace('','_').str.replace('(','').str.replace(')','')
#all_us_df

In [83]:
all_us_df.head()

  ___c___a___n___c___e___r___ ___t___y___p___e___  ... ___m___a___l___e___
0                       All cancer types combined  ...               487.9
1                  Brain and other nervous system  ...                 7.6
2                                          Breast  ...                 NaN
3                                          Cervix  ...                 NaN
4                        Colon (excluding rectum)  ...                28.1

[5 rows x 4 columns]

##### Importing the Death Estimates dataset

In [5]:

death_estimates_df = pd.read_excel("DeathEstimates.xlsx", sheet_name =1,header = 6,index_col = 'State')
death_estimates_df.drop(death_estimates_df.index[:5],inplace=True)

# Displaying the first five records

death_estimates_df.head(5)

                     All cancer types combined  ...  Vulva
State                                           ...
California                               60970  ...    NaN
Colorado                                  8170  ...    NaN
Connecticut                               6400  ...    NaN
Delaware                                  2200  ...    NaN
District of Columbia                      1010  ...    NaN

[5 rows x 55 columns]

#### Getting more information from the dataset

In [6]:
# Incident rate
incident_rate_df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 48 entries, California to Wyoming
Data columns (total 78 columns):
 #   Column                                                  Non-Null Count  Dtype
---  ------                                                  --------------  -----
 0   All cancer types combined / Both sexes combined         48 non-null     object
 1   All cancer types combined / Female                      48 non-null     object
 2   All cancer types combined / Male                        48 non-null     object
 3   Brain and other nervous system / Both sexes combined    48 non-null     object
 4   Brain and other nervous system / Female                 48 non-null     object
 5   Brain and other nervous system / Male                   48 non-null     object
 6   Breast / Both sexes combined                            48 non-null     object
 7   Breast / Female                                         48 non-null     object
 8   Breast / Male                                           0 non-null      float64
 9   Cervix / Both sexes combined                            48 non-null     object
 10  Cervix / Female                                         48 non-null     object
 11  Cervix / Male                                           0 non-null      float64
 12  Colon (excluding rectum) / Both sexes combined          0 non-null      float64
 13  Colon (excluding rectum) / Female                       0 non-null      float64
 14  Colon (excluding rectum) / Male                         0 non-null      float64
 15  Colorectum / Both sexes combined                        48 non-null     object
 16  Colorectum / Female                                     48 non-null     object
 17  Colorectum / Male                                       48 non-null     object
 18  Esophagus / Both sexes combined                         48 non-null     object
 19  Esophagus / Female                                      48 non-null     object
 20  Esophagus / Male                                        48 non-null     object
 21  Hodgkin lymphoma / Both sexes combined                  48 non-null     object
 22  Hodgkin lymphoma / Female                               48 non-null     object
 23  Hodgkin lymphoma / Male                                 48 non-null     object
 24  Kidney and renal pelvis / Both sexes combined           48 non-null     object
 25  Kidney and renal pelvis / Female                        48 non-null     object
 26  Kidney and renal pelvis / Male                          48 non-null     object
 27  Larynx / Both sexes combined                            48 non-null     object
 28  Larynx / Female                                         48 non-null     object
 29  Larynx / Male                                           48 non-null     object
 30  Leukemia / Both sexes combined                          48 non-null     object
 31  Leukemia / Female                                       48 non-null     object
 32  Leukemia / Male                                         48 non-null     object
 33  Liver and intrahepatic bile duct / Both sexes combined  48 non-null     object
 34  Liver and intrahepatic bile duct / Female               48 non-null     object
 35  Liver and intrahepatic bile duct / Male                 48 non-null     object
 36  Lung and bronchus / Both sexes combined                 48 non-null     object
 37  Lung and bronchus / Female                              48 non-null     object
 38  Lung and bronchus / Male                                48 non-null     object
 39  Melanoma of the skin / Both sexes combined              48 non-null     object
 40  Melanoma of the skin / Female                           48 non-null     object
 41  Melanoma of the skin / Male                             48 non-null     object
 42  Myeloma / Both sexes combined                           48 non-null     object
 43  Myeloma / Female                                        48 non-null     object
 44  Myeloma / Male                                          48 non-null     object
 45  Non-Hodgkin lymphoma / Both sexes combined              48 non-null     object
 46  Non-Hodgkin lymphoma / Female                           48 non-null     object
 47  Non-Hodgkin lymphoma / Male                             48 non-null     object
 48  Oral cavity and pharynx / Both sexes combined           48 non-null     object
 49  Oral cavity and pharynx / Female                        48 non-null     object
 50  Oral cavity and pharynx / Male                          48 non-null     object
 51  Ovary / Both sexes combined                             48 non-null     object
 52  Ovary / Female                                          48 non-null     object
 53  Ovary / Male                                            0 non-null      float64
 54  Pancreas / Both sexes combined                          48 non-null     object
 55  Pancreas / Female                                       48 non-null     object
 56  Pancreas / Male                                         48 non-null     object
 57  Prostate / Both sexes combined                          48 non-null     object
 58  Prostate / Female                                       0 non-null      float64
 59  Prostate / Male                                         48 non-null     object
 60  Rectum / Both sexes combined                            0 non-null      float64
 61  Rectum / Female                                         0 non-null      float64
 62  Rectum / Male                                           0 non-null      float64
 63  Stomach / Both sexes combined                           48 non-null     object
 64  Stomach / Female                                        48 non-null     object
 65  Stomach / Male                                          48 non-null     object
 66  Testis / Both sexes combined                            48 non-null     object
 67  Testis / Female                                         0 non-null      float64
 68  Testis / Male                                           48 non-null     object
 69  Thyroid / Both sexes combined                           48 non-null     object
 70  Thyroid / Female                                        48 non-null     object
 71  Thyroid / Male                                          48 non-null     object
 72  Urinary bladder / Both sexes combined                   48 non-null     object
 73  Urinary bladder / Female                                48 non-null     object
 74  Urinary bladder / Male                                  48 non-null     object
 75  Uterine corpus / Both sexes combined                    48 non-null     object
 76  Uterine corpus / Female                                 48 non-null     object
 77  Uterine corpus / Male                                   0 non-null      float64
dtypes: float64(12), object(66)
memory usage: 29.6+ KB

In [7]:
# Checking the shape

incident_rate_df.shape

(48, 78)

In [8]:
# New case estimate
new_case_estimates_df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 48 entries, California to Wyoming
Data columns (total 57 columns):
 #   Column                               Non-Null Count  Dtype
---  ------                               --------------  -----
 0   All cancer types combined            48 non-null     object
 1   Acute lymphocytic leukemia           0 non-null      float64
 2   Acute myeloid leukemia               0 non-null      float64
 3   Anus, anal canal and anorectum       0 non-null      float64
 4   Bones and joints                     0 non-null      float64
 5   Brain and other nervous system       48 non-null     object
 6   Breast                               48 non-null     object
 7   Cervix                               48 non-null     object
 8   Chronic lymphocytic leukemia         0 non-null      float64
 9   Chronic myeloid leukemia             0 non-null      float64
 10  Colon (excluding rectum)             0 non-null      float64
 11  Colorectum                           48 non-null     object
 12  Digestive system                     0 non-null      float64
 13  Endocrine system                     0 non-null      float64
 14  Esophagus                            48 non-null     object
 15  Eye and orbit                        0 non-null      float64
 16  Gallbladder and other biliary        0 non-null      float64
 17  Genital system                       0 non-null      float64
 18  Hodgkin lymphoma                     48 non-null     object
 19  Kidney and renal pelvis              48 non-null     object
 20  Larynx                               48 non-null     object
 21  Leukemia                             48 non-null     object
 22  Liver and intrahepatic bile duct     48 non-null     object
 23  Lung and bronchus                    48 non-null     object
 24  Lymphoma                             0 non-null      float64
 25  Melanoma of the skin                 48 non-null     object
 26  Mouth                                0 non-null      float64
 27  Myeloma                              48 non-null     object
 28  Non-Hodgkin lymphoma                 48 non-null     object
 29  Oral cavity and pharynx              48 non-null     object
 30  Other and unspecified primary sites  0 non-null      float64
 31  Other digestive organs               0 non-null      float64
 32  Other endocrine                      0 non-null      float64
 33  Other leukemia                       0 non-null      float64
 34  Other nonepithelial skin             0 non-null      float64
 35  Other oral cavity                    0 non-null      float64
 36  Other respiratory organs             0 non-null      float64
 37  Ovary                                48 non-null     object
 38  Pancreas                             48 non-null     object
 39  Penis and other male genital         0 non-null      float64
 40  Pharynx                              0 non-null      float64
 41  Prostate                             48 non-null     object
 42  Rectum                               0 non-null      float64
 43  Respiratory system                   0 non-null      float64
 44  Skin (excluding basal and squamous)  0 non-null      float64
 45  Small intestine                      0 non-null      float64
 46  Soft tissue (including heart)        0 non-null      float64
 47  Stomach                              48 non-null     object
 48  Testis                               48 non-null     object
 49  Thyroid                              48 non-null     object
 50  Tongue                               0 non-null      float64
 51  Ureter and other urinary organs      0 non-null      float64
 52  Urinary bladder                      48 non-null     object
 53  Urinary system                       0 non-null      float64
 54  Uterine corpus                       48 non-null     object
 55  Vagina and other female genital      0 non-null      float64
 56  Vulva                                0 non-null      float64
dtypes: float64(33), object(24)
memory usage: 21.8+ KB

In [9]:
# Checking the shape

new_case_estimates_df.shape

(48, 57)

In [10]:
# Death estimate

death_estimates_df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 48 entries, California to Wyoming
Data columns (total 55 columns):
 #   Column                               Non-Null Count  Dtype
---  ------                               --------------  -----
 0   All cancer types combined            48 non-null     object
 1   Acute lymphocytic leukemia           0 non-null      float64
 2   Acute myeloid leukemia               0 non-null      float64
 3   Anus, anal canal and anorectum       0 non-null      float64
 4   Bones and joints                     0 non-null      float64
 5   Brain and other nervous system       48 non-null     object
 6   Breast                               48 non-null     object
 7   Cervix                               48 non-null     object
 8   Chronic lymphocytic leukemia         0 non-null      float64
 9   Chronic myeloid leukemia             0 non-null      float64
 10  Colorectum                           48 non-null     object
 11  Digestive system                     0 non-null      float64
 12  Endocrine system                     0 non-null      float64
 13  Esophagus                            48 non-null     object
 14  Eye and orbit                        0 non-null      float64
 15  Gallbladder and other biliary        0 non-null      float64
 16  Genital system                       0 non-null      float64
 17  Hodgkin lymphoma                     0 non-null      float64
 18  Kidney and renal pelvis              48 non-null     object
 19  Larynx                               48 non-null     object
 20  Leukemia                             48 non-null     object
 21  Liver and intrahepatic bile duct     48 non-null     object
 22  Lung and bronchus                    48 non-null     object
 23  Lymphoma                             0 non-null      float64
 24  Melanoma of the skin                 48 non-null     object
 25  Mouth                                0 non-null      float64
 26  Myeloma                              48 non-null     object
 27  Non-Hodgkin lymphoma                 48 non-null     object
 28  Oral cavity and pharynx              48 non-null     object
 29  Other and unspecified primary sites  0 non-null      float64
 30  Other digestive organs               0 non-null      float64
 31  Other endocrine                      0 non-null      float64
 32  Other leukemia                       0 non-null      float64
 33  Other non-epithelial skin            0 non-null      float64
 34  Other oral cavity                    0 non-null      float64
 35  Other respiratory organs             0 non-null      float64
 36  Ovary                                48 non-null     object
 37  Pancreas                             48 non-null     object
 38  Penis and other male genital         0 non-null      float64
 39  Pharynx                              0 non-null      float64
 40  Prostate                             48 non-null     object
 41  Respiratory system                   0 non-null      float64
 42  Skin (excluding basal and squamous)  0 non-null      float64
 43  Small intestine                      0 non-null      float64
 44  Soft tissue (including heart)        0 non-null      float64
 45  Stomach                              48 non-null     object
 46  Testis                               0 non-null      float64
 47  Thyroid                              48 non-null     object
 48  Tongue                               0 non-null      float64
 49  Ureter and other urinary organs      0 non-null      float64
 50  Urinary bladder                      48 non-null     object
 51  Urinary system                       0 non-null      float64
 52  Uterine corpus                       48 non-null     object
 53  Vagina and other female genital      0 non-null      float64
 54  Vulva                                0 non-null      float64
dtypes: float64(33), object(22)
memory usage: 21.0+ KB

In [11]:
# Checking the shape

death_estimates_df.shape

(48, 55)

#### Checking the Columns

In [12]:
# Checking for the Incident rate

incident_rate_df.columns

Index(['All cancer types combined / Both sexes combined',
       'All cancer types combined / Female',
       'All cancer types combined / Male',
       'Brain and other nervous system / Both sexes combined',
       'Brain and other nervous system / Female',
       'Brain and other nervous system / Male', 'Breast / Both sexes combined',
       'Breast / Female', 'Breast / Male', 'Cervix / Both sexes combined',
       'Cervix / Female', 'Cervix / Male',
       'Colon (excluding rectum) / Both sexes combined',
       'Colon (excluding rectum) / Female', 'Colon (excluding rectum) / Male',
       'Colorectum / Both sexes combined', 'Colorectum / Female',
       'Colorectum / Male', 'Esophagus / Both sexes combined',
       'Esophagus / Female', 'Esophagus / Male',
       'Hodgkin lymphoma / Both sexes combined', 'Hodgkin lymphoma / Female',
       'Hodgkin lymphoma / Male',
       'Kidney and renal pelvis / Both sexes combined',
       'Kidney and renal pelvis / Female', 'Kidney and renal pelvis / Male',
       'Larynx / Both sexes combined', 'Larynx / Female', 'Larynx / Male',
       'Leukemia / Both sexes combined', 'Leukemia / Female',
       'Leukemia / Male',
       'Liver and intrahepatic bile duct / Both sexes combined',
       'Liver and intrahepatic bile duct / Female',
       'Liver and intrahepatic bile duct / Male',
       'Lung and bronchus / Both sexes combined', 'Lung and bronchus / Female',
       'Lung and bronchus / Male',
       'Melanoma of the skin / Both sexes combined',
       'Melanoma of the skin / Female', 'Melanoma of the skin / Male',
       'Myeloma / Both sexes combined', 'Myeloma / Female', 'Myeloma / Male',
       'Non-Hodgkin lymphoma / Both sexes combined',
       'Non-Hodgkin lymphoma / Female', 'Non-Hodgkin lymphoma / Male',
       'Oral cavity and pharynx / Both sexes combined',
       'Oral cavity and pharynx / Female', 'Oral cavity and pharynx / Male',
       'Ovary / Both sexes combined', 'Ovary / Female', 'Ovary / Male',
       'Pancreas / Both sexes combined', 'Pancreas / Female',
       'Pancreas / Male', 'Prostate / Both sexes combined',
       'Prostate / Female', 'Prostate / Male', 'Rectum / Both sexes combined',
       'Rectum / Female', 'Rectum / Male', 'Stomach / Both sexes combined',
       'Stomach / Female', 'Stomach / Male', 'Testis / Both sexes combined',
       'Testis / Female', 'Testis / Male', 'Thyroid / Both sexes combined',
       'Thyroid / Female', 'Thyroid / Male',
       'Urinary bladder / Both sexes combined', 'Urinary bladder / Female',
       'Urinary bladder / Male', 'Uterine corpus / Both sexes combined',
       'Uterine corpus / Female', 'Uterine corpus / Male'],
      dtype='object')

In [13]:
# Checking for the New Case estimates

new_case_estimates_df.columns

Index(['All cancer types combined', 'Acute lymphocytic leukemia',
       'Acute myeloid leukemia', 'Anus, anal canal and anorectum',
       'Bones and joints', 'Brain and other nervous system', 'Breast',
       'Cervix', 'Chronic lymphocytic leukemia', 'Chronic myeloid leukemia',
       'Colon (excluding rectum)', 'Colorectum', 'Digestive system',
       'Endocrine system', 'Esophagus', 'Eye and orbit',
       'Gallbladder and other biliary', 'Genital system', 'Hodgkin lymphoma',
       'Kidney and renal pelvis', 'Larynx', 'Leukemia',
       'Liver and intrahepatic bile duct', 'Lung and bronchus', 'Lymphoma',
       'Melanoma of the skin', 'Mouth', 'Myeloma', 'Non-Hodgkin lymphoma',
       'Oral cavity and pharynx', 'Other and unspecified primary sites',
       'Other digestive organs', 'Other endocrine', 'Other leukemia',
       'Other nonepithelial skin', 'Other oral cavity',
       'Other respiratory organs', 'Ovary', 'Pancreas',
       'Penis and other male genital', 'Pharynx', 'Prostate', 'Rectum',
       'Respiratory system', 'Skin (excluding basal and squamous)',
       'Small intestine', 'Soft tissue (including heart)', 'Stomach', 'Testis',
       'Thyroid', 'Tongue', 'Ureter and other urinary organs',
       'Urinary bladder', 'Urinary system', 'Uterine corpus',
       'Vagina and other female genital', 'Vulva'],
      dtype='object')

In [14]:
# Checking for the Death estimates

death_estimates_df.columns

Index(['All cancer types combined', 'Acute lymphocytic leukemia',
       'Acute myeloid leukemia', 'Anus, anal canal and anorectum',
       'Bones and joints', 'Brain and other nervous system', 'Breast',
       'Cervix', 'Chronic lymphocytic leukemia', 'Chronic myeloid leukemia',
       'Colorectum', 'Digestive system', 'Endocrine system', 'Esophagus',
       'Eye and orbit', 'Gallbladder and other biliary', 'Genital system',
       'Hodgkin lymphoma', 'Kidney and renal pelvis', 'Larynx', 'Leukemia',
       'Liver and intrahepatic bile duct', 'Lung and bronchus', 'Lymphoma',
       'Melanoma of the skin', 'Mouth', 'Myeloma', 'Non-Hodgkin lymphoma',
       'Oral cavity and pharynx', 'Other and unspecified primary sites',
       'Other digestive organs', 'Other endocrine', 'Other leukemia',
       'Other non-epithelial skin', 'Other oral cavity',
       'Other respiratory organs', 'Ovary', 'Pancreas',
       'Penis and other male genital', 'Pharynx', 'Prostate',
       'Respiratory system', 'Skin (excluding basal and squamous)',
       'Small intestine', 'Soft tissue (including heart)', 'Stomach', 'Testis',
       'Thyroid', 'Tongue', 'Ureter and other urinary organs',
       'Urinary bladder', 'Urinary system', 'Uterine corpus',
       'Vagina and other female genital', 'Vulva'],
      dtype='object')

#### Data Cleaning

##### Checking for Null Values

In [15]:
# Checking for the Incident rate

incident_rate_df.isnull().sum()

All cancer types combined / Both sexes combined          0
All cancer types combined / Female                       0
All cancer types combined / Male                         0
Brain and other nervous system / Both sexes combined     0
Brain and other nervous system / Female                  0
                                                        ..
Urinary bladder / Female                                 0
Urinary bladder / Male                                   0
Uterine corpus / Both sexes combined                     0
Uterine corpus / Female                                  0
Uterine corpus / Male                                   48
Length: 78, dtype: int64

In [16]:
# Checking for the Death Estimates

death_estimates_df.isnull().sum()

All cancer types combined               0
Acute lymphocytic leukemia             48
Acute myeloid leukemia                 48
Anus, anal canal and anorectum         48
Bones and joints                       48
Brain and other nervous system          0
Breast                                  0
Cervix                                  0
Chronic lymphocytic leukemia           48
Chronic myeloid leukemia               48
Colorectum                              0
Digestive system                       48
Endocrine system                       48
Esophagus                               0
Eye and orbit                          48
Gallbladder and other biliary          48
Genital system                         48
Hodgkin lymphoma                       48
Kidney and renal pelvis                 0
Larynx                                  0
Leukemia                                0
Liver and intrahepatic bile duct        0
Lung and bronchus                       0
Lymphoma                               48
Melanoma of the skin                    0
Mouth                                  48
Myeloma                                 0
Non-Hodgkin lymphoma                    0
Oral cavity and pharynx                 0
Other and unspecified primary sites    48
Other digestive organs                 48
Other endocrine                        48
Other leukemia                         48
Other non-epithelial skin              48
Other oral cavity                      48
Other respiratory organs               48
Ovary                                   0
Pancreas                                0
Penis and other male genital           48
Pharynx                                48
Prostate                                0
Respiratory system                     48
Skin (excluding basal and squamous)    48
Small intestine                        48
Soft tissue (including heart)          48
Stomach                                 0
Testis                                 48
Thyroid                                 0
Tongue                                 48
Ureter and other urinary organs        48
Urinary bladder                         0
Urinary system                         48
Uterine corpus                          0
Vagina and other female genital        48
Vulva                                  48
dtype: int64

**HAVING LOADED ALL OUR DATASETS LET'S GO FURTHER AND DO MORE ANALYSIS**

In [17]:
#CHECKING FOR NULL VALUES
# Checking for the New Estimates

new_case_estimates_df.isnull()

                      All cancer types combined  ...  Vulva
State                                            ...
California                                False  ...   True
Colorado                                  False  ...   True
Connecticut                               False  ...   True
Delaware                                  False  ...   True
District of Columbia                      False  ...   True
Florida                                   False  ...   True
Georgia                                   False  ...   True
Hawaii                                    False  ...   True
Idaho                                     False  ...   True
Illinois                                  False  ...   True
Indiana                                   False  ...   True
Iowa                                      False  ...   True
Kansas                                    False  ...   True
Kentucky                                  False  ...   True
Louisiana                                 False  ...   True
Maine                                     False  ...   True
Maryland                                  False  ...   True
Massachusetts                             False  ...   True
Michigan                                  False  ...   True
Minnesota                                 False  ...   True
Mississippi                               False  ...   True
Missouri                                  False  ...   True
Montana                                   False  ...   True
Nebraska                                  False  ...   True
Nevada                                    False  ...   True
New Hampshire                             False  ...   True
New Jersey                                False  ...   True
New Mexico                                False  ...   True
New York                                  False  ...   True
North Carolina                            False  ...   True
North Dakota                              False  ...   True
Ohio                                      False  ...   True
Oklahoma                                  False  ...   True
Oregon                                    False  ...   True
Pennsylvania                              False  ...   True
Puerto Rico                               False  ...   True
Rhode Island                              False  ...   True
South Carolina                            False  ...   True
South Dakota                              False  ...   True
Tennessee                                 False  ...   True
Texas                                     False  ...   True
Utah                                      False  ...   True
Vermont                                   False  ...   True
Virginia                                  False  ...   True
Washington                                False  ...   True
West Virginia                             False  ...   True
Wisconsin                                 False  ...   True
Wyoming                                   False  ...   True

[48 rows x 57 columns]

**AS WE CAN SEE FROM ABOVE WE HAVE SOO MANY NULL VALUES DROPPING THEM WILL LEAD TO A HUGE LOSS OF DATA AS SHOWN BELOW**

In [18]:
new_castle_dropped=new_case_estimates_df.dropna()
new_castle_dropped.head()

Empty DataFrame
Columns: [All cancer types combined, Acute lymphocytic leukemia, Acute myeloid leukemia, Anus, anal canal and anorectum, Bones and joints, Brain and other nervous system, Breast, Cervix, Chronic lymphocytic leukemia, Chronic myeloid leukemia, Colon (excluding rectum), Colorectum, Digestive system, Endocrine system, Esophagus, Eye and orbit, Gallbladder and other biliary, Genital system, Hodgkin lymphoma, Kidney and renal pelvis, Larynx, Leukemia, Liver and intrahepatic bile duct, Lung and bronchus, Lymphoma, Melanoma of the skin, Mouth, Myeloma, Non-Hodgkin lymphoma, Oral cavity and pharynx, Other and unspecified primary sites, Other digestive organs, Other endocrine, Other leukemia, Other nonepithelial skin, Other oral cavity, Other respiratory organs, Ovary, Pancreas, Penis and other male genital, Pharynx, Prostate, Rectum, Respiratory system, Skin (excluding basal and squamous), Small intestine, Soft tissue (including heart), Stomach, Testis, Thyroid, Tongue, Ureter and other urinary organs, Urinary bladder, Urinary system, Uterine corpus, Vagina and other female genital, Vulva]
Index: []

In [19]:
#OUR ORIGINAL SHAPE OF OUR DATA
new_case_estimates_df.shape

(48, 57)

In [20]:
#AS YOU CAN SEE FROM THE SHAPE OF OUR NEW DATA FRAME WITH ALL NaN VALUES DROPPED WE ACTUALLY LOST ALL OUR 43 ROWS AS SEEN FROM 
#OUR HEAD ABOVE.
new_castle_dropped.shape

(0, 57)

**Dropping NaN values will not be an option in this case**

##### Replacing the Null values with "0"

In [21]:
# Replacing for Incident rate dataset

incident_rate_df.fillna(0,inplace=True)
incident_rate_df.head()

                     All cancer types combined / Both sexes combined  ... Uterine corpus / Male
State                                                                 ...
California                                                     402.4  ...                   0.0
Colorado                                                       396.7  ...                   0.0
Connecticut                                                    465.1  ...                   0.0
Delaware                                                       488.2  ...                   0.0
District of Columbia                                             426  ...                   0.0

[5 rows x 78 columns]

****

In [22]:
# Replacing null values for New case estimates dataset with 0

new_case_estimates_df.fillna(0,inplace=True)
new_case_estimates_df.head()

                     All cancer types combined  ...  Vulva
State                                           ...
California                              189220  ...    0.0
Colorado                                 28480  ...    0.0
Connecticut                              22810  ...    0.0
Delaware                                  7080  ...    0.0
District of Columbia                      3440  ...    0.0

[5 rows x 57 columns]

In [23]:
# Lets Preview our Death estimates dataset below

death_estimates_df.head()

                     All cancer types combined  ...  Vulva
State                                           ...
California                               60970  ...    NaN
Colorado                                  8170  ...    NaN
Connecticut                               6400  ...    NaN
Delaware                                  2200  ...    NaN
District of Columbia                      1010  ...    NaN

[5 rows x 55 columns]

**Since we have no data on certain types of Cancers we will Drop them for now as our study will be unfounded. We will go further to study the cancers that we actually have data on.**

In [24]:
#Dropping columns with no Data
death_estimates_df.dropna(axis=1, how='all', inplace=True)
death_estimates_df.head()

                     All cancer types combined  ... Uterine corpus
State                                           ...
California                               60970  ...           1480
Colorado                                  8170  ...            180
Connecticut                               6400  ...            120
Delaware                                  2200  ...             50
District of Columbia                      1010  ...             50

[5 rows x 22 columns]

In [25]:
death_estimates_df.shape

(48, 22)

**WE CAN STILL NOTE STRING ENTRIES ENTERED WHERE INT' VALUES SHOULD BE ENTERED, WE WILL CONVERT THE COLUMN VALUES INTO FLOAT DTYPE AND REMOVE THE STRINGS WE SEE ABOVE SUCH AS "NOT AVAILABLE" WHEN WE CAN JUST USE ZERO(0) INFACT LETS PREVIEW OUR DTYPES**

In [26]:
death_estimates_df.dtypes

All cancer types combined           object
Brain and other nervous system      object
Breast                              object
Cervix                              object
Colorectum                          object
Esophagus                           object
Kidney and renal pelvis             object
Larynx                              object
Leukemia                            object
Liver and intrahepatic bile duct    object
Lung and bronchus                   object
Melanoma of the skin                object
Myeloma                             object
Non-Hodgkin lymphoma                object
Oral cavity and pharynx             object
Ovary                               object
Pancreas                            object
Prostate                            object
Stomach                             object
Thyroid                             object
Urinary bladder                     object
Uterine corpus                      object
dtype: object

**NOTE ABOVE THAT THE COLUMNS DTYPE IS AN OBJECT THIS IS NOT PROPER ESPECIALLY IF WE WANT TO DO STATISTICAL COMPUTATIONS WITH THESE COLUMNS, WE WILL GO AHEAD AND CONVERT THEM**

In [27]:
#We can do this by writing a function to replace all non_int values into an int like "0" or a a null value 
#thereafter we can fill the null values later on with either the mean, mode or any value that 
#computationally makes sense based on our dataset
#for now we will just replace these "Strings" with null values see below...

In [28]:
#Check below..,you'll notice both string values and int values entered in the same columns, this is not good practice.
death_estimates_df.values

array([['60970', '2070', '4690 - Female breast cancer only.', ..., '310',
        '1620', '1480'],
       ['8170', '310', '670 - Female breast cancer only.', ...,
        'Not available - Estimate is fewer than 50 cases or deaths.',
        '250', '180'],
       ['6400', '210', '420 - Female breast cancer only.', ...,
        'Not available - Estimate is fewer than 50 cases or deaths.',
        '180', '120'],
       ...,
       ['4460', '120', '290 - Female breast cancer only.', ...,
        'Not available - Estimate is fewer than 50 cases or deaths.',
        '130', '70'],
       ['11570', '370', '720 - Female breast cancer only.', ..., '50',
        '300', '220'],
       ['1000',
        'Not available - Estimate is fewer than 50 cases or deaths.',
        '70 - Female breast cancer only.', ...,
        'Not available - Estimate is fewer than 50 cases or deaths.',
        'Not available - Estimate is fewer than 50 cases or deaths.',
        'Not available - Estimate is fewer than 50 cases or deaths.']],
      dtype=object)

**CONVERTING OUR COLUMN VALUES TO NUMERIC**

In [29]:
New_death_estimate_df=death_estimates_df.apply(pd.to_numeric, errors='coerce', axis=1)
New_death_estimate_df.head()

                      All cancer types combined  ...  Uterine corpus
State                                            ...
California                              60970.0  ...          1480.0
Colorado                                 8170.0  ...           180.0
Connecticut                              6400.0  ...           120.0
Delaware                                 2200.0  ...            50.0
District of Columbia                     1010.0  ...            50.0

[5 rows x 22 columns]

In [30]:
#PROCEEDING TO DROP MORE NaN VALUES WHERE A COLUMN COMPLETELY HAS NO VALUE.
#NOTE THAT INITIALLY THESE COLUMNS WERE NOT DROPPED BECAUSE THEY WERE FILLED 
#WITH STRING VALUES THAT WE JUST DROPPED ABOVE. 

New_death_estimate_df.dropna(axis=1, how='all', inplace=True)
New_death_estimate_df.head(10)

                      All cancer types combined  ...  Uterine corpus
State                                            ...
California                              60970.0  ...          1480.0
Colorado                                 8170.0  ...           180.0
Connecticut                              6400.0  ...           120.0
Delaware                                 2200.0  ...            50.0
District of Columbia                     1010.0  ...            50.0
Florida                                 47540.0  ...           920.0
Georgia                                 18750.0  ...           310.0
Hawaii                                   2590.0  ...            60.0
Idaho                                    3240.0  ...            60.0
Illinois                                23200.0  ...           560.0

[10 rows x 21 columns]

In [31]:
New_death_estimate_df.shape

(48, 21)

**Looks a bit better now, we will now fill the remaining 'Nan' values. Remember the goal is to preserve as much as possible the original data values we have instead of dropping all the Nan values all at once, this is how we end up loosing all our data and its not good practice**

In [32]:

#FILLING REMAINING 'NaN' VALUES 
#We will use a Backward fill and a Forward Fill simultaneously to ensure no Nan values are left

New_death_estimate_df.fillna(0,inplace=True)
New_death_estimate_df.head(10)

                      All cancer types combined  ...  Uterine corpus
State                                            ...
California                              60970.0  ...          1480.0
Colorado                                 8170.0  ...           180.0
Connecticut                              6400.0  ...           120.0
Delaware                                 2200.0  ...            50.0
District of Columbia                     1010.0  ...            50.0
Florida                                 47540.0  ...           920.0
Georgia                                 18750.0  ...           310.0
Hawaii                                   2590.0  ...            60.0
Idaho                                    3240.0  ...            60.0
Illinois                                23200.0  ...           560.0

[10 rows x 21 columns]

**OUR DATASET LOOKS ALOT CLEANER NOW**

In [33]:
New_death_estimate_df.dtypes

All cancer types combined           float64
Brain and other nervous system      float64
Cervix                              float64
Colorectum                          float64
Esophagus                           float64
Kidney and renal pelvis             float64
Larynx                              float64
Leukemia                            float64
Liver and intrahepatic bile duct    float64
Lung and bronchus                   float64
Melanoma of the skin                float64
Myeloma                             float64
Non-Hodgkin lymphoma                float64
Oral cavity and pharynx             float64
Ovary                               float64
Pancreas                            float64
Prostate                            float64
Stomach                             float64
Thyroid                             float64
Urinary bladder                     float64
Uterine corpus                      float64
dtype: object

**NEW CASE ESTIMATE DATASET**

In [34]:
#Previewing our new case estimate dataset
new_case_estimates_df.head()

                     All cancer types combined  ...  Vulva
State                                           ...
California                              189220  ...    0.0
Colorado                                 28480  ...    0.0
Connecticut                              22810  ...    0.0
Delaware                                  7080  ...    0.0
District of Columbia                      3440  ...    0.0

[5 rows x 57 columns]

In [35]:
new_case_estimates_df.values

array([['189220', 0.0, 0.0, ..., '7470', 0.0, 0.0],
       ['28480', 0.0, 0.0, ..., '940', 0.0, 0.0],
       ['22810', 0.0, 0.0, ..., '830', 0.0, 0.0],
       ...,
       ['12690', 0.0, 0.0, ..., '490', 0.0, 0.0],
       ['37320', 0.0, 0.0, ..., '1380', 0.0, 0.0],
       ['3140', 0.0, 0.0, ..., '100', 0.0, 0.0]], dtype=object)

**CONVERTING OUR COLUMN VALUES TO NUMERIC**

In [36]:
new_case_estimates_df=new_case_estimates_df.apply(pd.to_numeric, errors='coerce', axis=1)
new_case_estimates_df.head()

                      All cancer types combined  ...  Vulva
State                                            ...
California                             189220.0  ...    0.0
Colorado                                28480.0  ...    0.0
Connecticut                             22810.0  ...    0.0
Delaware                                 7080.0  ...    0.0
District of Columbia                     3440.0  ...    0.0

[5 rows x 57 columns]

In [37]:
#Dropping columns with no Data
new_case_estimates_df.dropna(axis=1, how='all', inplace=True)
new_case_estimates_df.head(10)

                      All cancer types combined  ...  Vulva
State                                            ...
California                             189220.0  ...    0.0
Colorado                                28480.0  ...    0.0
Connecticut                             22810.0  ...    0.0
Delaware                                 7080.0  ...    0.0
District of Columbia                     3440.0  ...    0.0
Florida                                152600.0  ...    0.0
Georgia                                 58970.0  ...    0.0
Hawaii                                   7730.0  ...    0.0
Idaho                                   10440.0  ...    0.0
Illinois                                75350.0  ...    0.0

[10 rows x 56 columns]

In [38]:
#REPLACING 'nan' VALUES WITH 0
new_case_estimates_df.fillna(0,inplace=True)
new_case_estimates_df.head()

                      All cancer types combined  ...  Vulva
State                                            ...
California                             189220.0  ...    0.0
Colorado                                28480.0  ...    0.0
Connecticut                             22810.0  ...    0.0
Delaware                                 7080.0  ...    0.0
District of Columbia                     3440.0  ...    0.0

[5 rows x 56 columns]

In [39]:
new_case_estimates_df.shape

(48, 56)

**INCIDENT RATE DATASET**

In [40]:
#Previewing the Dataset
incident_rate_df.head()

                     All cancer types combined / Both sexes combined  ... Uterine corpus / Male
State                                                                 ...
California                                                     402.4  ...                   0.0
Colorado                                                       396.7  ...                   0.0
Connecticut                                                    465.1  ...                   0.0
Delaware                                                       488.2  ...                   0.0
District of Columbia                                             426  ...                   0.0

[5 rows x 78 columns]

In [41]:
#CONVERTING COLUMN VALUES TO NUMERIC
incident_rate_df=incident_rate_df.apply(pd.to_numeric, errors='coerce', axis=1)
incident_rate_df.head(10)

                      All cancer types combined / Both sexes combined  ...  Uterine corpus / Male
State                                                                  ...
California                                                      402.4  ...                    0.0
Colorado                                                        396.7  ...                    0.0
Connecticut                                                     465.1  ...                    0.0
Delaware                                                        488.2  ...                    0.0
District of Columbia                                            426.0  ...                    0.0
Florida                                                         460.2  ...                    0.0
Georgia                                                         468.5  ...                    0.0
Hawaii                                                          415.5  ...                    0.0
Idaho                                                           445.1  ...                    0.0
Illinois                                                        466.8  ...                    0.0

[10 rows x 78 columns]

In [42]:
#Dropping columns with no Data

incident_rate_df.dropna(axis=1, how='all', inplace=True)
incident_rate_df.head(10)

                      All cancer types combined / Both sexes combined  ...  Uterine corpus / Male
State                                                                  ...
California                                                      402.4  ...                    0.0
Colorado                                                        396.7  ...                    0.0
Connecticut                                                     465.1  ...                    0.0
Delaware                                                        488.2  ...                    0.0
District of Columbia                                            426.0  ...                    0.0
Florida                                                         460.2  ...                    0.0
Georgia                                                         468.5  ...                    0.0
Hawaii                                                          415.5  ...                    0.0
Idaho                                                           445.1  ...                    0.0
Illinois                                                        466.8  ...                    0.0

[10 rows x 78 columns]

In [43]:
#REPLACING 'nan' VALUES WITH 0
incident_rate_df.fillna(0,inplace=True)
incident_rate_df.head()

                      All cancer types combined / Both sexes combined  ...  Uterine corpus / Male
State                                                                  ...
California                                                      402.4  ...                    0.0
Colorado                                                        396.7  ...                    0.0
Connecticut                                                     465.1  ...                    0.0
Delaware                                                        488.2  ...                    0.0
District of Columbia                                            426.0  ...                    0.0

[5 rows x 78 columns]

In [44]:
#incident_rate_df.columns
#We can Do More to Rename the column names, specify separator and Delimeter
#code below...

In [45]:
incident_rate_df['Breast / Both sexes combined'].values

array([  0. ,   0. ,   0. ,   0. ,   0. ,   0. ,   0. ,   0. ,   0. ,
         0. ,   0. ,   0. , 131.6,   0. ,   0. ,   0. ,   0. ,   0. ,
         0. , 134.2,   0. ,   0. ,   0. ,   0. ,   0. ,   0. ,   0. ,
         0. ,   0. ,   0. ,   0. ,   0. ,   0. ,   0. ,   0. ,   0. ,
         0. ,   0. ,   0. ,   0. ,   0. ,   0. ,   0. ,   0. ,   0. ,
         0. ,   0. ,   0. ])

In [46]:
incident_rate_df.dtypes

All cancer types combined / Both sexes combined         float64
All cancer types combined / Female                      float64
All cancer types combined / Male                        float64
Brain and other nervous system / Both sexes combined    float64
Brain and other nervous system / Female                 float64
                                                         ...
Urinary bladder / Female                                float64
Urinary bladder / Male                                  float64
Uterine corpus / Both sexes combined                    float64
Uterine corpus / Female                                 float64
Uterine corpus / Male                                   float64
Length: 78, dtype: object

In [47]:
incident_rate_df.head()

                      All cancer types combined / Both sexes combined  ...  Uterine corpus / Male
State                                                                  ...
California                                                      402.4  ...                    0.0
Colorado                                                        396.7  ...                    0.0
Connecticut                                                     465.1  ...                    0.0
Delaware                                                        488.2  ...                    0.0
District of Columbia                                            426.0  ...                    0.0

[5 rows x 78 columns]

**THESE ARE OUR CLEANED DATASETS**

**incident_rate_df**

**new_case_estimates_df**

**New_death_estimate_df**

In [48]:

incident_rate_df.head()

                      All cancer types combined / Both sexes combined  ...  Uterine corpus / Male
State                                                                  ...
California                                                      402.4  ...                    0.0
Colorado                                                        396.7  ...                    0.0
Connecticut                                                     465.1  ...                    0.0
Delaware                                                        488.2  ...                    0.0
District of Columbia                                            426.0  ...                    0.0

[5 rows x 78 columns]

In [49]:
#incident_rate_df['Breast / Both sexes combined'].max

In [50]:
new_case_estimates_df.head()

                      All cancer types combined  ...  Vulva
State                                            ...
California                             189220.0  ...    0.0
Colorado                                28480.0  ...    0.0
Connecticut                             22810.0  ...    0.0
Delaware                                 7080.0  ...    0.0
District of Columbia                     3440.0  ...    0.0

[5 rows x 56 columns]

In [51]:
New_death_estimate_df.head()

                      All cancer types combined  ...  Uterine corpus
State                                            ...
California                              60970.0  ...          1480.0
Colorado                                 8170.0  ...           180.0
Connecticut                              6400.0  ...           120.0
Delaware                                 2200.0  ...            50.0
District of Columbia                     1010.0  ...            50.0

[5 rows x 21 columns]

**DESCRIPTIVE STATISTICS OF OUR DATA**

In [52]:
#INCIDENT RATE DATASET
incident_rate_df.describe()

       All cancer types combined / Both sexes combined  ...  Uterine corpus / Male
count                                        48.000000  ...                   48.0
mean                                        435.302083  ...                    0.0
std                                          96.088850  ...                    0.0
min                                           0.000000  ...                    0.0
25%                                         439.425000  ...                    0.0
50%                                         458.550000  ...                    0.0
75%                                         470.325000  ...                    0.0
max                                         519.600000  ...                    0.0

[8 rows x 78 columns]

In [53]:
#NEW CASE ESTIMATES DATASET
new_case_estimates_df.describe()

       All cancer types combined  ...  Vulva
count                  48.000000  ...   48.0
mean                38041.041667  ...    0.0
std                 40862.260393  ...    0.0
min                     0.000000  ...    0.0
25%                 10345.000000  ...    0.0
50%                 26805.000000  ...    0.0
75%                 43632.500000  ...    0.0
max                189220.000000  ...    0.0

[8 rows x 56 columns]

In [54]:
#NEW DEATH ESTIMATE DATASET
New_death_estimate_df.describe()

       All cancer types combined  ...  Uterine corpus
count                  48.000000  ...       48.000000
mean                12044.375000  ...      247.708333
std                 12756.845289  ...      294.916069
min                     0.000000  ...        0.000000
25%                  3390.000000  ...       60.000000
50%                  8540.000000  ...      135.000000
75%                 14612.500000  ...      302.500000
max                 60970.000000  ...     1480.000000

[8 rows x 21 columns]

**ANSWERING RESEARCH QUESTIONS**

Which is the most prevalent type of cancer across all States  (highest number of incidences)?

In [55]:
#Sorted
incident_rate_df.sort_values(by='State', axis=0, ascending=False, inplace=True)
incident_rate_df.head()

               All cancer types combined / Both sexes combined  ...  Uterine corpus / Male
State                                                           ...
Wyoming                                                  402.1  ...                    0.0
Wisconsin                                                468.6  ...                    0.0
West Virginia                                            478.9  ...                    0.0
Washington                                               442.4  ...                    0.0
Virginia                                                 411.0  ...                    0.0

[5 rows x 78 columns]

In [57]:
#incident_rate_df.groupby(['State']).max()

#incident_rate_df.head(10)

#incident_rate_df.columns.values

In [59]:
#incident_rate_df.columns